'#__user_keys':
    name: '#__user_keys'
    from:
        - '#__user_keys'
    columns:
        id: { Field: id, Type: 'int(10) unsigned', 'Null': 'NO', Default: null, Extra: auto_increment, Comment: '', From: [id] }
        user_id: { Field: user_id, Type: varchar(150), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [user_id] }
        token: { Field: token, Type: varchar(255), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [token] }
        series: { Field: series, Type: varchar(191), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [series] }
        invalid: { Field: invalid, Type: tinyint(4), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [invalid] }
        time: { Field: time, Type: varchar(200), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [time] }
        uastring: { Field: uastring, Type: varchar(255), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [uastring] }
    index:
        - { Table: '#__user_keys', Non_unique: '0', Key_name: PRIMARY, Seq_in_index: '1', Column_name: id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_keys', Non_unique: '0', Key_name: series, Seq_in_index: '1', Column_name: series, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_keys', Non_unique: '0', Key_name: series_2, Seq_in_index: '1', Column_name: series, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_keys', Non_unique: '0', Key_name: series_3, Seq_in_index: '1', Column_name: series, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_keys', Non_unique: '1', Key_name: user_id, Seq_in_index: '1', Column_name: user_id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
'#__user_notes':
    name: '#__user_notes'
    from:
        - '#__user_notes'
    columns:
        id: { Field: id, Type: 'int(10) unsigned', 'Null': 'NO', Default: null, Extra: auto_increment, Comment: '', From: [id] }
        user_id: { Field: user_id, Type: 'int(10) unsigned', 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [user_id] }
        catid: { Field: catid, Type: 'int(10) unsigned', 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [catid] }
        subject: { Field: subject, Type: varchar(100), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [subject] }
        body: { Field: body, Type: mediumtext, 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [body] }
        state: { Field: state, Type: tinyint(3), 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [state] }
        checked_out: { Field: checked_out, Type: 'int(10) unsigned', 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [checked_out] }
        checked_out_time: { Field: checked_out_time, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [checked_out_time] }
        created_user_id: { Field: created_user_id, Type: 'int(10) unsigned', 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [created_user_id] }
        created_time: { Field: created_time, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [created_time] }
        modified_user_id: { Field: modified_user_id, Type: 'int(10) unsigned', 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [modified_user_id] }
        modified_time: { Field: modified_time, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [modified_time] }
        review_time: { Field: review_time, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [review_time] }
        publish_up: { Field: publish_up, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [publish_up] }
        publish_down: { Field: publish_down, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [publish_down] }
    index:
        - { Table: '#__user_notes', Non_unique: '0', Key_name: PRIMARY, Seq_in_index: '1', Column_name: id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_notes', Non_unique: '1', Key_name: idx_user_id, Seq_in_index: '1', Column_name: user_id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_notes', Non_unique: '1', Key_name: idx_category_id, Seq_in_index: '1', Column_name: catid, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
'#__user_profiles':
    name: '#__user_profiles'
    from:
        - '#__user_profiles'
    columns:
        user_id: { Field: user_id, Type: int(11), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [user_id] }
        profile_key: { Field: profile_key, Type: varchar(100), 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [profile_key] }
        profile_value: { Field: profile_value, Type: mediumtext, 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [profile_value] }
        ordering: { Field: ordering, Type: int(11), 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [ordering] }
    index:
        - { Table: '#__user_profiles', Non_unique: '0', Key_name: idx_user_id_profile_key, Seq_in_index: '1', Column_name: user_id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_profiles', Non_unique: '0', Key_name: idx_user_id_profile_key, Seq_in_index: '2', Column_name: profile_key, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
'#__user_usergroup_map':
    name: '#__user_usergroup_map'
    from:
        - '#__user_usergroup_map'
    columns:
        user_id: { Field: user_id, Type: 'int(10) unsigned', 'Null': 'NO', Default: '0', Extra: '', Comment: 'Foreign Key to #__users.id', From: [user_id] }
        group_id: { Field: group_id, Type: 'int(10) unsigned', 'Null': 'NO', Default: '0', Extra: '', Comment: 'Foreign Key to #__usergroups.id', From: [group_id] }
    index:
        - { Table: '#__user_usergroup_map', Non_unique: '0', Key_name: PRIMARY, Seq_in_index: '1', Column_name: user_id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__user_usergroup_map', Non_unique: '0', Key_name: PRIMARY, Seq_in_index: '2', Column_name: group_id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
    data:
        - ['1', '8']
'#__usergroups':
    name: '#__usergroups'
    from:
        - '#__usergroups'
    columns:
        id: { Field: id, Type: 'int(10) unsigned', 'Null': 'NO', Default: null, Extra: auto_increment, Comment: 'Primary Key', From: [id] }
        parent_id: { Field: parent_id, Type: 'int(10) unsigned', 'Null': 'NO', Default: '0', Extra: '', Comment: 'Adjacency List Reference Id', From: [parent_id] }
        lft: { Field: lft, Type: int(11), 'Null': 'NO', Default: '0', Extra: '', Comment: 'Nested set lft.', From: [lft] }
        rgt: { Field: rgt, Type: int(11), 'Null': 'NO', Default: '0', Extra: '', Comment: 'Nested set rgt.', From: [rgt] }
        title: { Field: title, Type: varchar(100), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [title] }
    index:
        - { Table: '#__usergroups', Non_unique: '0', Key_name: PRIMARY, Seq_in_index: '1', Column_name: id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__usergroups', Non_unique: '0', Key_name: idx_usergroup_parent_title_lookup, Seq_in_index: '1', Column_name: parent_id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__usergroups', Non_unique: '0', Key_name: idx_usergroup_parent_title_lookup, Seq_in_index: '2', Column_name: title, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__usergroups', Non_unique: '1', Key_name: idx_usergroup_title_lookup, Seq_in_index: '1', Column_name: title, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__usergroups', Non_unique: '1', Key_name: idx_usergroup_adjacency_lookup, Seq_in_index: '1', Column_name: parent_id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__usergroups', Non_unique: '1', Key_name: idx_usergroup_nested_set_lookup, Seq_in_index: '1', Column_name: lft, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__usergroups', Non_unique: '1', Key_name: idx_usergroup_nested_set_lookup, Seq_in_index: '2', Column_name: rgt, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
    data:
        - ['1', '0', '1', '18', Public]
        - ['2', '1', '8', '15', Registered]
        - ['3', '2', '9', '14', Author]
        - ['4', '3', '10', '13', Editor]
        - ['5', '4', '11', '12', Publisher]
        - ['6', '1', '4', '7', Manager]
        - ['7', '6', '5', '6', Administrator]
        - ['8', '1', '16', '17', 'Super Users']
        - ['9', '1', '2', '3', Guest]
'#__users':
    name: '#__users'
    from:
        - '#__users'
    columns:
        id: { Field: id, Type: int(11), 'Null': 'NO', Default: null, Extra: auto_increment, Comment: '', From: [id] }
        name: { Field: name, Type: varchar(400), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [name] }
        username: { Field: username, Type: varchar(150), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [username] }
        email: { Field: email, Type: varchar(100), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [email] }
        password: { Field: password, Type: varchar(100), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [password] }
        block: { Field: block, Type: tinyint(4), 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [block] }
        sendEmail: { Field: sendEmail, Type: tinyint(4), 'Null': 'YES', Default: '0', Extra: '', Comment: '', From: [sendEmail] }
        registerDate: { Field: registerDate, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [registerDate] }
        lastvisitDate: { Field: lastvisitDate, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: '', From: [lastvisitDate] }
        activation: { Field: activation, Type: varchar(100), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [activation] }
        params: { Field: params, Type: mediumtext, 'Null': 'NO', Default: null, Extra: '', Comment: '', From: [params] }
        lastResetTime: { Field: lastResetTime, Type: datetime, 'Null': 'NO', Default: '0000-00-00 00:00:00', Extra: '', Comment: 'Date of last password reset', From: [lastResetTime] }
        resetCount: { Field: resetCount, Type: int(11), 'Null': 'NO', Default: '0', Extra: '', Comment: 'Count of password resets since lastResetTime', From: [resetCount] }
        otpKey: { Field: otpKey, Type: varchar(1000), 'Null': 'NO', Default: '', Extra: '', Comment: 'Two factor authentication encrypted keys', From: [otpKey] }
        otep: { Field: otep, Type: varchar(1000), 'Null': 'NO', Default: '', Extra: '', Comment: 'One time emergency passwords', From: [otep] }
        requireReset: { Field: requireReset, Type: tinyint(4), 'Null': 'NO', Default: '0', Extra: '', Comment: 'Require user to reset password on next login', From: [requireReset] }
    index:
        - { Table: '#__users', Non_unique: '0', Key_name: PRIMARY, Seq_in_index: '1', Column_name: id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__users', Non_unique: '1', Key_name: idx_block, Seq_in_index: '1', Column_name: block, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__users', Non_unique: '1', Key_name: username, Seq_in_index: '1', Column_name: username, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__users', Non_unique: '1', Key_name: email, Seq_in_index: '1', Column_name: email, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__users', Non_unique: '1', Key_name: idx_name, Seq_in_index: '1', Column_name: name, Sub_part: '100', 'Null': '', Comment: '', Index_comment: '' }
    data:
        - ['1', LYRASOFT, lyrasoft, service@lyrasoft.net, $2y$10$r2790HebS29K35l39YzgQelNJ.GxcUlDOxXYlUykDMHNZGtvV5Wli, '0', '1', '2015-12-13 14:18:06', '2016-06-01 07:58:07', '', '{}', '0000-00-00 00:00:00', '0', '', '', '0']
'#__viewlevels':
    name: '#__viewlevels'
    from:
        - '#__viewlevels'
    columns:
        id: { Field: id, Type: 'int(10) unsigned', 'Null': 'NO', Default: null, Extra: auto_increment, Comment: 'Primary Key', From: [id] }
        title: { Field: title, Type: varchar(100), 'Null': 'NO', Default: '', Extra: '', Comment: '', From: [title] }
        ordering: { Field: ordering, Type: int(11), 'Null': 'NO', Default: '0', Extra: '', Comment: '', From: [ordering] }
        rules: { Field: rules, Type: varchar(5120), 'Null': 'NO', Default: null, Extra: '', Comment: 'JSON encoded access control.', From: [rules] }
    index:
        - { Table: '#__viewlevels', Non_unique: '0', Key_name: PRIMARY, Seq_in_index: '1', Column_name: id, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
        - { Table: '#__viewlevels', Non_unique: '0', Key_name: idx_assetgroup_title_lookup, Seq_in_index: '1', Column_name: title, Sub_part: null, 'Null': '', Comment: '', Index_comment: '' }
    data:
        - ['1', Public, '0', '[1]']
        - ['2', Registered, '2', '[6,2,8]']
        - ['3', Special, '3', '[6,3,8]']
        - ['5', Guest, '1', '[9]']
        - ['6', 'Super Users', '4', '[8]']
